[workspace]
members = ["crates/checklist-sync", "crates/checklist-relay"]

[package]
name = "checklist-tui"
version = "0.1.6"
edition = "2024"
license = "MIT"
description = "A TUI for keeping track of your tasks in slim terminal views"
readme = "README.md"
repository = "https://github.com/dylanfair/checklist"
keywords = ["tui", "todo", "task", "terminal", "dashboard"]
categories = ["command-line-interface"]
exclude = ["images/"]

[profiler.release]
lto = true
codegen-units = 1

[[bin]]
name = "checklist"
path = "src/main.rs"
bench = false

[dependencies]
anyhow = "1.0.86"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.13", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.29.0"
directories = "6.0.0"
ratatui = { version = "0.30.0", features = ["serde"] }
rusqlite = { version = "0.40.0", features = ["bundled", "chrono", "uuid"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
struct-field-names-as-array = "0.3.0"
strum = { version = "0.28.0", features = ["strum_macros"] }
strum_macros = "0.28.0"
toml = "1.1.2+spec-1.1.0"
uuid = { version = "1.10.0", features = ["v4"] }
